# https://taskfile.dev

version: "3"
tasks:
  init:
    desc: Run Terraform init and point to a specific environments statefile.
    preconditions:
      - sh: test -f ./{{.CLI_ARGS}}.tfvars
        msg: "You must pass the name of a configured environment."
    cmds:
      - terraform init -reconfigure -backend-config="key=ajb-azure-exercise/{{.CLI_ARGS}}/terraform.tfstate"
  plan:
    deps: [init]
    desc: Run Terraform init and point to a specific environments statefile.
    preconditions:
      - sh: test -f ./{{.CLI_ARGS}}.tfvars
        msg: "You must pass the name of a configured environment."
    cmds:
      - terraform plan -var-file={{.CLI_ARGS}}.tfvars
